Added Cloudflare
robchahin/sso-wall-of-shame pull request #199
Opened 2021-02-27 22:30 UTC by garrett-wood

Added Cloudflare with Pricing based on quote.

2021-03-15 02:19 UTC, SaphireLattice commented
Why does it link to something other than CloudFlare?

2021-03-18 23:24 UTC, Wild1145 requested changes

2021-03-18 23:24 UTC, Wild1145 commented on _data/vendors.yml
> +  url: https://cloudsploit.com
Don't think you updated the link from copying the Cloudsploit one.

2021-09-06 19:51 UTC, merged

2023-01-12 00:09 UTC, abracadabra2 commented
Please Re-Add Cloudflare!

2023-01-12 01:17 UTC, mbainter commented
This probably should reflect the product. The zero trust product has no SSO tax, so I'm assuming this is one of their other offerings.