feat: add docker
robchahin/sso-wall-of-shame pull request #240
Opened 2021-08-31 17:36 UTC by DonMagee

Docker has a new pricing model that charges extra for SSO.

Source: https://www.docker.com/blog/updating-product-subscriptions/
and https://www.docker.com/pricing

2021-08-31 20:23 UTC, w0de requested changes
Was halfway through adding my own PR for Docker when I saw yours. Figured I'd help!

2021-08-31 20:23 UTC, w0de commented on _data/vendors.yml
> +  percent_increase: 33%
This is a 300% increase (if one isn't pedantic with per _cent_ but that's another review)

2021-08-31 20:24 UTC, w0de commented on _data/vendors.yml
> +  sso_pricing: $21 per u/m
```suggestion
  sso_pricing: $21 per u/m
  footnotes: "[^docker]: SSO "coming soon" as of 08/21 so you may just be paying for the promise!"
```

2021-08-31 20:24 UTC, w0de commented on _data/vendors.yml
> +  percent_increase: 33%
```suggestion
  percent_increase: 300%
```

2022-04-10 07:32 UTC, lcycon commented
Fixed in #273

2022-04-10 07:32 UTC, closed without merging