Whitesource SSO info
robchahin/sso-wall-of-shame pull request #92
Opened 2019-11-06 22:28 UTC by jwalker

2021-09-09 08:33 UTC, NovaAtWarren requested changes
Values out of date, otherwise good

2021-09-09 08:33 UTC, NovaAtWarren commented on _data/vendors.yml
> +  sso_pricing: $3,0000 per year
Might want to change this to $28,000, to reflect pricing changes and increase legibility.

2021-09-09 08:33 UTC, NovaAtWarren commented on _data/vendors.yml
> +  base_pricing: $250 per month
Base price was changed to $120 / year

2024-07-23 00:50 UTC, p-linnane commented
WhiteSource has been replaced by Mend.io per https://www.whitesourcesoftware.com.

This PR can probably be closed.

2024-08-16 05:06 UTC, closed without merging